# This script should check whether files are in the folder they are supposed to be in by filetype

name: Check branch name

on:
  workflow_call:

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project # to gain access to the branch names
      uses: actions/checkout@v2

    - name: Set up Git
      run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"

    - name: Get branch name
      run: | 
        echo "Branch name is: ${GITHUB_REF#refs/heads/}"
