# This script should check whether files are in the folder they are supposed to be in by filetype

name: Check branch name

on:
  workflow_call:

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project # to gain access to the branch names
      uses: actions/checkout@v2

    - name: Check branch name
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        if [[ $BRANCH_NAME == *"dev"* ]]; then
          echo "Branch name contains 'dev'. Workflow will continue."
        else
          echo "Branch name does not contain 'dev'. Workflow will be skipped."
          exit 1 # Use a non-zero exit code to indicate skipping the workflow
