# This script will call the python scripts

name: Run Python

on:
  workflow_call:

jobs:
  run-python:
    name: Run Python
    runs-on: ubuntu-latest
    steps:
    - name: Check-out repository
      uses: actions/checkout@v2

    - name: Run Python
      run: python ./python/run-check.py
      shell: sh
